version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql


  server:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - database
      networks:
        - default
      ports:
      - "8080:8080"
      env_file:
      - ./.env
